### ISSUE TITLE
Use of Station Status - is_installed to track removed/uninstalled stations

### ISSUE THREAD

**Issue by johnclary** [MobilityData/gbfs#101]
We (Austin) have a number of stations that have been uninstalled (or were installed temporarily) and are not listed in our station_status feed. I assume that is_installed should be a means for keeping track of such stations, but I've checked a handful of other feeds (Denver, Madison, Houston), and I don't see any stations listed with a status of is_installed = 0.

Would the is_installed field be an appropriate means for tracking uninstalled stations? Any idea why cities aren't using it? This leads to a situation (in Austin, at least) where we have trip data with station IDs that are not in our station_status feed. I realize this issue may be outside the scope of GBFS, but I'm curious to hear from interested parties.

**Comment by mplsmitch** [comment]
In Minneapolis we operate seasonally, removing all 200+ stations every winter. In the off season I set all of my stations to is_installed=0. I also use it if we have a new location permit to mark the location until the equipment gets installed. If we remove station temporarily, for example to accommodate construction, we'll set it to 0. If we remove a station permanently then it gets removed from the feeds.  If the station isn't coming back, I wouldn't put it in your feed, too much chance for misinterpretations by users.

**Comment by jcn** [comment]
> Would the is_installed field be an appropriate means for tracking uninstalled stations? Any idea why cities aren't using it?

The tricky thing is that you're talking about mixing historical data with realtime data. GBFS is intended to be a realtime data source. I believe what you're talking about is a trip history dump where historical stations may or may not still be in service. GBFS wasn't meant to handle this case, simply because it would not make sense for realtime clients to have to download historical station data. In the case of trip data sources, I would suggest that those also include all station data for the period of that dump.

**Comment by johnclary** [comment]
This is helpful, thanks. I agree that if GBFS is intended to be a real-time "feed" it does not make sense to serve historical content.
