### ISSUE TITLE
Allowed Travel Areas?

### ISSUE THREAD

**Issue by christrillium** [MobilityData/gbfs#185]
Geofenced zones enable us to describe ares where rides might not be able to start, end, go through, or have other limitations.

However, are there currently any use cases where the allowed travel area needs to be specified? e.g. "All travel outside of a specified area is forbidden."

**Comment by mplsmitch** [comment]
What you're describing is a very common scenario although it's largely fell
on cities to enforce. Most any dockless operation has a designated service
area in which they are permitted to operate.  For example they may be
permitted within  city boundaries but not in the adjoining municipalities.
When a vehicle crosses the city boundary it leaves the permitted service
area and is then operating unlawfully/without a permit. Some systems
(Car2go for example) have been configured to prevent rentals from being
closed when the vehicle is outside the permitted service area.

**Comment by christrillium** [comment]
Good point! Thanks Mitch.

**Comment by matt-wirtz** [comment]
Hi,

from my understanding the operation area, in which you are allowed to operate/drive the rented vehicle, is described by system_regions.json. (related to #173, #183) But it lacks the geographic object which would describe the boundaries.

What I think is quite common here is to use JSON multipoint-polygons which can have the type “allowed for parking”, “not allowed for parking”, "allowed for driving" and "not allowed for driving". The “not allowed” type supersedes the “allowed” type. So e.g. you can have small “not allowed” polygons inside the larger “allowed” polygon.

So I think it might be useful to add a geo-object and a type attribute to the system_regions.json in order to be able to describe the allowed parking and driving areas. Valuable information for the user.

**Comment by christrillium** [comment]
Hi Matt, 

Thanks for your response. Check out [PR#175](https://github.com/NABSA/gbfs/pull/175). It is getting close to a vote and addresses your points.
