### ISSUE TITLE
License of data available in systems.csv

### ISSUE THREAD

**Issue by bartoliniii** [MobilityData/gbfs#309]
I'm looking information about license of GBFS feeds stored in systems.csv but unfortunately I didn't find such an information. So I have some questions:

- If any feed is published in systems.csv it means that it can by used by any app (e.g. mobility aggregator)?
- is there any "minimal" license restriction to publish feed url in systems.csv? 
- if not, maybe it would be worth extending the system.csv file with license information (e.g. link or license type) in each record of new data?

Thanks for any help and explanations!

**Comment by mplsmitch** [comment]
Q: _If any feed is published in systems.csv it means that it can by used by any app (e.g. mobility aggregator)?_

A: No - inclusion in systems.csv does not imply any kind of license. You would need to check each feed for license information. Look at `systems_information.json  - license_url` for the location of any license. Many feeds listed in systems.csv are either not licensed or do not publish license information.  A lot of the feeds listed in `systems.csv` were added by the community, not by their publishers so `systems.csv` shouldn't be viewed as a source of truth - always look to the actual feed for information about the data.

Q: _is there any "minimal" license restriction to publish feed url in systems.csv?_

A: Currently there is not a licensing requirement for inclusion in systems.csv. Licensing info will be required in starting with v3.0 of the specification and we are considering whether it should be a requirement for inclusion in the systems catalog.  Currently if it were required the systems catalog would be much smaller because so few feeds publish licensing info.

Q: _if not, maybe it would be worth extending the system.csv file with license information (e.g. link or license type) in each record of new data?_
A: Inclusion of license info is one of the changes under consideration for the systems catalog. There's an open discussion in #249 about possible changes and improvements. It would be helpful if you could also add any additional thoughts you have to that issue.

Hope that helps

**Comment by bartoliniii** [comment]
@mplsmitch Thank you for your comprehensive answer!
It would definitely be useful because this is the data that you don't know if you can use :-)
I will take part in the discussion in https://github.com/NABSA/gbfs/issues/249
