### ISSUE TITLE
station_id field requirements/definition

### ISSUE THREAD

**Issue by serialc** [MobilityData/gbfs#31]
I cannot find where the station_id field requirements are clearly defined.
It says "See Output Format above for ID field requirements" [here](https://github.com/NABSA/gbfs/blob/master/gbfs.md#station_informationjson)

What's the (my) issue?
I'm not clear as to what the line is referring to regarding the 'Output Format'
While many systems use integers we have some such as:
bcycle_spartanburg_1924
bcycle_linkdayton_3025
So clearly the unofficial requirement is a string. Of what length then? 32 characters?

I'm not sure if there's some overall guidelines that's being followed - such as freedom and flexibility vs compactness and clarity...

Getting to the point, I wonder if station ids shouldn't be defined as integers? I'm fine with a string too. Either way a maximum length should be defined. 32? 64?

Further I wonder if all fields should have a clearly defined type and maximum character/digit length?

This will help those storing these values in databases with predefined fields sizes.

**Comment by mdarveau** [comment]
You are right; something is missing in the 'Output Format'. I tried to look at the draft's history in the google doc, but it doesn't seem to be available anymore.

I think we should add something along the lines of: "station_id: string(max 255 characters), should be stable enough to be persisted by applications. Example usage: persistence of favorite stations."

**Comment by jcn** [comment]
This is outlined in the "file requirements" section at the top of the document:

ID fields in the document should be represented as strings that identify that particular object. They:
must be unique within like fields (bike_id must be unique among bikes)
do not have to be globally unique
must not contain spaces
should be persistent for a given object (station, plan, etc)
Given since we don't want to dictate the internal structure of any provider's systems, ID fields were specifically designed to be strings (and not integers).

**Comment by fruminator** [comment]
I think we should close this issue.

**Comment by jcn** [comment]
Merged in some slight restructuring in https://github.com/NABSA/gbfs/pull/32 to make this info more apparent. Closing.
