### ISSUE TITLE
Bikeshare central GPS coords added to system_information.json file

### ISSUE THREAD

**Issue by rolinger** [MobilityData/gbfs#35]
Hi all...this is now my 2nd request for feature enhancement.

I am developing a rideshare aggregator app.   Thus I am taking a national and multi-national approach to designing my app services.  Lyft/Uber/Taxi rideshares, Bikeshares, and public transit are integrated into my app. 

I have already integrated the SoBi API.  But now I am expanding to add the non-SoBi bikeshares listed in the GBFS csv file - I am actually excited I came across this GBFS...it literally doubles that amount of locations I can show available bikeshares to my users.  Within the SoBi API I can do a quick "network" check with a single call to see if a bikeshare is in the city my user is inquiring from.  But not so with the GBFS data.

There needs to be a central GPS coordinates in the system-information.json file - or a full address with zipcode - that can allow me to do a single call for the top level json file to determine if that network is even near/available to my user...then if it is, go deeper into the lower level json files to get bike/station information.  As is, "Phoenix" as the location field in the root system.csv simply isn't good enough for me to do a top level check.

**Comment by serialc** [comment]
This wouldn't be of much help to you I think. Some systems span quite a wide area making the centre too far from your user's location while still potentially having a station close by as described in the "station information" feed.

Why don't you just generate (repeatedly and automatically) the centroid or, better yet, the coverage area of each bike-share system (BSS) yourself based on station information feeds? Your users would then download **your** BSS points or coverage and determine if they are in proximity or inside a polygon containing bike-share.

The central location of a BSS is subjective anyways. Having a lat/lng in the system_information.json would require an update when any stations are moved or added (if we're talking about centre of mass/centroid). Another reason this is meaningless is that there may be no stations close to the centre of the system. Look at [Miami](http://citibikemiami.com/station-map) or [San Francisco](http://www.bayareabikeshare.com/stations) and you'll see that the central location would be in the water.

I suggest closing this.

**Comment by nackko** [comment]
Hey @rolinger,

I'm also a third party dev. I'll let the power to be answer your remark regarding GBFS design but in the meantime I'd like to make you aware of citybik.es, that allow to make just the kind of requests you're mentioning. I'm using it in a multi city app that automagically grab the data corresponding to the closest system of shared bikes.
http://api.citybik.es/v2/
@serialc is right, sometimes there are spatial configurations that are a bit tricky, but it's so much better than having to maintain the centroid or coverage area ourselves !

**Comment by rolinger** [comment]
@serialc - I do see your point.  Though I believe some solution should be suggested.  If someone's gps coordinates have them 5 miles away, but in a different city - the only way to see if stations are nearby is go to deeper into the json levels.  The idea is prevent from having to loop into deeper json levels and do recursive look ups on distance between the user and each station.  If nothing exists at that city, why be forced to do further look ups just to see that nothing exists.

@f8full - wow, thanks for the heads up on that API.  I have had my head buried in so many other aspects of my app that I never looked up to see that there were other networks besides SoBi.  Thus I was just excited to see the GBFS.  This api you have pointed me to,who maintains it - who's network is it (or is a mix of bikeshare networks?).  Looking at the map I see it doesn't list any of the city's that SoBi is in, thus telling me its 'another' network or one exclusive of SoBi.  Not that I am married to anyone network or SoBi, just realizing that to be more inclusive of all networks I am going to have to program for different APIs, GBFS, etc.  

You have anymore links/info on that api/citybikes?  That api page doesn't provide much info.

**Comment by serialc** [comment]
I wasn't clear.

On your server have a script that weekly/monthly or whatever generates the centroid of each BSS by getting the location of all stations in each system and exports the mean or whatever to your server. Your application then uses this list of BSS, similar to systems.csv
 but with lat/lng. GBFS is one specification. You're going to need to get the centroids for all BSS anyways. GBFS is still only available for relatively few BSS. Having GBFS change to suit your needs won't help you in the end as you'll still need to get the central lat/lng for other systems anyways.

You can use https://github.com/eskerda/pybikes to get much of the data.

**Comment by nackko** [comment]
@rolinger You're welcome !
who maintains it ? I gues that'd be @eskerda, it's all on github :dart: 
https://github.com/eskerda/pybikes
:D
As far as I can tell, it's any network for which someone wrote a python script to either scrape or parse a datasource. Anyone can add any city, for themselves and the world at large at the same time. So it's a colleciton of networks yes.
I guess sobi is too different from station based system to be easily integrated.
Yes, GBFS won't solve it all for us, we'll have to deal with a mix, maybe (I chose to stick to citybik.es only). And when it comes to complex features like payment... we'll see what happens :)

Full disclosure : I been following citybik.es project passively for years (since 2012) and contacted them recentrly to be added to the project page
http://citybik.es/projects
I supposed you already consulted
http://citybik.es/about

The API doc is in the link I sent you, if you read Java, you can also get an idea by looking at the source code of the Android app I'm writing.
https://github.com/f8full/ludOScity/tree/master/FindMyBikes/app/src/main/java/com/ludoscity/findmybikes/citybik_es

Hope that helps ! Lemme know, I might want to integrate sobi indeed ! ;)

**Comment by nackko** [comment]
As far as the feature you mentionned
Yes, @serialc could be a way to go, though writing and maintaining such server could be some kind of a pain (eased by GBFS MUCH, for sure, thks them for that).
The best would be for whoever produces the list of station data to also provided some well defined additional information (like the centroïd, but that doesn't cover all cases), but way better, bounds definition, or a collection of ones for disjointed network (think bay area bikeshare).
That'd be two Lat/Lng couple per bound (two corners)
See as a sample :
LatLng
https://developers.google.com/android/reference/com/google/android/gms/maps/model/LatLng
LatLngBounds
https://developers.google.com/android/reference/com/google/android/gms/maps/model/LatLngBounds

That way, inside/outside tests have more precision.

From my experience, having the center like citybik.es provides is a good compromise that gave way ton only one bug in NYC : I had to obliterate an other network that is close but not integrated with citibike.
`if (closestNetwork.id.equalsIgnoreCase(NEW_YORK_HUDSON_BIKESHARE_ID)){
                    closestNetwork = answerList.get(1); //will contain citibike
                }`
https://github.com/f8full/ludOScity/blob/94527cddd572e32d80a9a2817bd2ec23a4626276/FindMyBikes/app/src/main/java/com/ludoscity/findmybikes/activities/NearbyActivity.java (line 2146)

So that'd be my request for inclusion in GBFS standard : a couple of calculated Lat/Lng (so, 4 numbers) or a collection of them for disjointed networks, calculated every time the station list is updated.

**Comment by antrim** [comment]
Is anyone using system_regions.json for the function described here? (#173)

Would the proposal for geofenced areas respond to this? (#175)

**Comment by heidiguenin** [comment]
I'm going to go ahead and close this issue on Jan 3rd, 2020 unless there's a response to the questions @antrim asked in October or anyone wants to chime in with further discussion or a proposal.
