### ISSUE TITLE
Specify type for POSIX time stamp fields

### ISSUE THREAD

**Issue by afischer** [MobilityData/gbfs#42]
Currently, the spec doesn't specify a type for time stamps. This has caused some systems to represent them as ints, while others represent them as strings.  More amusingly, some systems use both.

Example: BCycle-Charlotte currently uses a string representation in their [`gbfs.json`](https://gbfs.bcycle.com/bcycle_charlotte/gbfs.json), but integers in [`system_status.json`](https://gbfs.bcycle.com/bcycle_charlotte/station_status.json). (This actually seems to be the case for all BCycle feeds, so that may be an error on their part.)

@jcn pointed out that [the POSIX time spec does not specify a type or encoding](https://en.wikipedia.org/wiki/Unix_time#Representing_the_number), but we agree that an integer makes the most sense in this situation.

**Comment by jcn** [comment]
It looks like SoBi systems use integers consistently, and BCycle and 8D systems are inconsistent. 

Since one of the benefits of using POSIX is actually being able to easily do timestamp math, we should clarify the spec to specify integers. 

Since we're already inconsistent across (and within) systems, parsers probably already need to jump through some hoops during ingestion, so I don't think this will be considered a breaking change. I propose that we clarify the spec, and systems should modify their feeds as is convenient for them.

**Comment by jcn** [comment]
Closed by #48
