### ISSUE TITLE
Clarify/Codify Localization URL Routing

### ISSUE THREAD

**Issue by afischer** [MobilityData/gbfs#46]
The [current localization rules](https://github.com/NABSA/gbfs/blob/master/gbfs.md#localization) allows but does not require feeds to have the `ISO-639` 2 letter language code in the URL. The wording implies that if the bike share intends to only serve the files in one language.

**Examples:**
- SoBi and B-Cycle feeds that only provide english data place all feeds at the autodiscovery root. See http://boise.greenbike.com/opendata/gbfs.json, http://boise.greenbike.com/opendata/system_information.json, https://gbfs.bcycle.com/bcycle_charlotte/gbfs.json
- Motivate and PBSC feeds use the /en/ or /fr/ routes, regardless of if there is one or multiple languages.

**Issues**
While this is not an issue if a developer pulls URLs from the auto discovery URL, it is often faster to link directly to the necessary feeds for the sake of speed. By having this ambiguity, it is more difficult for a developer to build URL strings without first parsing the auto discovery `gbfs.json` feed, as it is not clear whether to append `/lang/feed.json` or just `/feed.json` to the GBFS root.

**Possible Solutions**
1. [Breaking] Mandate that feeds be nested under a `ISO-639` `/lang/` route.
2. [Breaking, but less overhead] Require developers to serve their default language when no language parameters are specified, and any additional languages must be nested in a `/lang/` route<a href="#f1">¹</a>.
3. Do nothing at all, and recommend developers always refer to the auto discovery feed.

While this is not a large issue, it has caused URL routes of GBFS feeds to be inconsistent. I would argue that solution 1 would be the most correct, with 3 being the most feasible.

Thoughts? I’d love to hear from developers and how you poll GBFS feeds—do you store the direct URLs? Parse the auto discovery?

---

<a name="f1">¹</a> This could be problematic as someone parsing without using lang parameters would return different languages between systems.

**Comment by mdarveau** [comment]
Hi,

I don't understand how one could build the URL string without looking at the auto discovery `gbfs.json`. The spec does not specify where all the JSON files should be located. It could be in a sub path or even on another subdomain (a CDN for example).

For example, the Montreal's scheme at `www.bixi.com` publishes data at `http://api-core.bixi.com/gbfs/gbfs.json`. NYC at `http://www.citibikenyc.com` publishes at `http://api-core.citibikenyc.com/gbfs/gbfs.json`. The `api-core` part is common to all 8D's backed systems but this should not be assumed.

Actually, even the location of the `gbfs.json` file should not be assumed. Ideally, it would be parsed from the HTML of the system's web site. See `Auto-Discovery` in https://github.com/NABSA/gbfs/blob/master/gbfs.md.

**Comment by barbeau** [comment]
> Actually, even the location of the gbfs.json file should not be assumed. Ideally, it would be parsed from the HTML of the system's web site.

IMHO, that sounds a bit crazy - scraping HTML isn't something I'd ever recommend for a production system.  It does get the point of where this information should be retrieved from, though, and needing a centralized directory of GBFS feeds, though (see https://github.com/NABSA/gbfs/issues/28).

> I don't understand how one could build the URL string without looking at the auto discovery gbfs.json

As @afischer mentioned, you often want to avoid additional round trips between consumer/producer as much as possible.  So, much like you'd need to store the `gbfs.json` URL, you might as well just store the direct URLs to the other endpoints.  And because `gbfs.json` is optional (even though it seems to be widely supported), then developers can't always rely on that discovery mechanism, so we need to design for storing these endpoint URLs directly anyway.

This brings me to a related question, though - are GBFS producers making the assumption that consumers will _always_ consume `gbfs.json` directly, if that API is provided for a given feed?  For example, would any GBFS producers change an API endpoint URL without first announcing it to the consumers/developer community, assuming that consumers would automatically pick up the change from the auto-discovery `gbfs.json`?

This has implications for designing consumer logic, including caching (even temporarily) the API endpoints directly without first referencing `gbfs.json`.

> Thoughts? I’d love to hear from developers and how you poll GBFS feeds—do you store the direct URLs? Parse the auto discovery?

In our OpenTripPlanner implementation in Tampa, FL (with a SoBi-based system - https://usf.socialbicycles.com/), we're polling `station_information.json`, `station_status.json`, and `free_bike_status.json` directly.  We aren't polling `gbfs.json` as all (hence my above question).  This design can be seen in the PR we recently opened to merge GBFS support back into the main OTP project - https://github.com/opentripplanner/OpenTripPlanner/pull/2315.

**Comment by tedder** [comment]
> scraping HTML isn't something I'd ever recommend for a production system. It does get the point of where this information should be retrieved from, though, and needing a centralized directory of GBFS feeds, though (see #28).

`<link rel` is fantastic. Just like RSS feeds and FB:OG data, why should there be a centralized location of decentralized data?

**Comment by barbeau** [comment]
> Just like RSS feeds and FB:OG data, why should there be a centralized location of decentralized data?

Because if you're building a multi-region consumer, you have to build your own repository of feed URLs.  This makes life harder for the consumers, and everyone is duplicating the same work.  This centralized location effectively already exists in [`systems.csv`](https://github.com/NABSA/gbfs/blob/master/systems.csv) in this repository.  #28 just asks the question if we could rely on that being programmatically queried.

The same questions were asked about GTFS, and the community has gone through a number of registries/directories, including [gtfs-data-exchange.com](http://www.gtfs-data-exchange.com/), [transitfeeds.com](http://transitfeeds.com/), and [Transitland](https://transit.land/).  The need is definitely there.

**Comment by tedder** [comment]
> Because if you're building a multi-region consumer

Sure- but there's value in both, it seems.

**Comment by mdarveau** [comment]
> This brings me to a related question, though - are GBFS producers making the assumption that consumers will always consume gbfs.json directly, if that API is provided for a given feed? For example, would any GBFS producers change an API endpoint URL without first announcing it to the consumers/developer community, assuming that consumers would automatically pick up the change from the auto-discovery gbfs.json?

We try not to break existing consumers as much as we can. :-) We would keep the old feed location for some time and check logs to confirm no one are using them before decommissioning it.
I think auto-discovery only makes the transition easier.

> This has implications for designing consumer logic, including caching (even temporarily) the API endpoints directly without first referencing gbfs.json.

I totally understand. It wouldn't make sense to request consumers first to call gbfs.json before every call to station_status.json.

**Comment by afischer** [comment]
Going to close this as it seems out of scope for this spec; as long as the endpoints in a vendors autodiscovery are correct, consumers should be okay finding your feeds.
