### ISSUE TITLE
Stations listed twice

### ISSUE THREAD

**Issue by sergip76** [MobilityData/gbfs#535]
Some bike systems like Citibike in New York lists each station twice.
I'm using the listed url:
https://gbfs.lyft.com/gbfs/1.1/bkn/en/station_information.json

**Comment by richfab** [comment]
Hello Sergi! Thank you for raising this data quality issue.

I have informed Lyft of this issue.

Please note that the open source online [GBFS validator](https://gbfs-validator.mobilitydata.org/) will soon allow producers to identify the case that you mentioned. With the PR [#106](https://github.com/MobilityData/gbfs-validator/pull/106), the validator will raise an error when `station_information.json` or `station_status.json` contain duplicate `station_id`. 

Thank you for your contribution!

**Comment by mplsmitch** [comment]
@richfab  I've noticed when you have a big system like Citibike or Divvy with low data quality there are so many errors that the validator fails because the response is too large:
https://gbfs-validator.mobilitydata.org/validator?url=https%3A%2F%2Fgbfs.divvybikes.com%2Fgbfs%2Fgbfs.json
Returns:
`{ "errorMessage": "Response payload size exceeded maximum allowed payload size (6291556 bytes).", "errorType": "Function.ResponseSizeTooLarge" }`

**Comment by richfab** [comment]
Hi @mplsmitch! Thank you for flagging this issue. 

A response payload size exceeded issue is open on the GBFS validator repo: https://github.com/MobilityData/gbfs-validator/issues/109.

I hope this issue can be resolved shortly. Thank you!

**Comment by merjakaj** [comment]
@richfab When looking at the data for Citi Bike from NYC, it looks like the duplicate stations started to appear from August 4. Hopefully this will help troubleshooting this situation.

**Comment by ArashMansouri** [comment]
Thanks for flagging this issue. The problem with the stations appearing twice on the citibike feed has now been resolved.

**Comment by richfab** [comment]
I confirm that there is no longer any duplicate station in https://gbfs.lyft.com/gbfs/1.1/bkn/en/station_information.json. 
Thank you @ArashMansouri for resolving this issue so quickly.
