### ISSUE TITLE
Add `ID` to `systems.csv`

### ISSUE THREAD

**Issue by cka-y** [MobilityData/gbfs#664]
### What is the issue and _why_ is it an issue?
Currently, in `systems.csv`, there is no way to uniquely identify a feed. While the `System ID` should be unique according to the specification, some operators do not adhere to this rule. This leads to ambiguity and potential issues in feed tracking and management. To address this, I propose introducing an `ID` column that is automatically populated. This would ensure that each feed has a unique identifier, facilitating reliable automated script ingestion and enabling accurate feed tracking and history tracing.

### Please describe some potential solutions you have considered (even if they aren’t related to GBFS).
One potential solution is to generate the ID by combining the `system_id` with an index for feeds sharing that system_id. For example, if three feeds have the system ID `system_abc`, their IDs could be `system_abc_1`, `system_abc_2`, and `system_abc_3`. Feeds with an already unique identifier in systems.csv will have the same value in `ID` and `System ID`.

### Is your potential solution a breaking change?
- [ ] Yes 
- [x] No
- [ ] Unsure

**Comment by mplsmitch** [comment]
I'm fully in support of this however I'm not sure it solves the issue. As I understand it, you want a way to uniquely identify feeds so as to avoid duplication. I can't point to any examples off hand but I've seen many times in the past where feeds are duplicated. Sometimes this is done by a single producer and sometimes it's the result of an aggregator like Entur, Mobidata etc. In the former, the feed is available at multiple URLs, but the feed data and `system_id` is the same for each. In the later case, one comes from the owner of the system and the other from the aggregator and `system_id` may not match because the aggregator has assigned their own.  In either case there's still potential for duplication.  So given that, is a adding another ID field any better than just assigning an ID to each new line in the file as you ingest it?

Having said that it would be a workaround for cases like Helbiz and Neuron that have heaps of feeds using the same `system_id`.

I think part of the problem is that no where in the specification do we clearly define what constitutes a system, so we end up with cases like Helbiz and Neuron where they should be assigning a different `system_id` for each city but instead they treat all of Helbiz as a  "system" under a single ID, or HELLO CYCLING where a single feed covers all of Japan. I proposed a system definition in #306 but it didn't make the final cut.

**Comment by richfab** [comment]
Thank you @mplsmitch for these insights!

>As I understand it, you want a way to uniquely identify feeds so as to avoid duplication

In fact, we want a way to uniquely identify a system, not a feed. Unfortunately the `system_id` from `system_information.json` does not allow this because some operators use the same `system_id` for several distinct systems, as you correctly noted for Helbiz and Neuron.

>Sometimes it's the result of an aggregator

In the case of multiple feeds for the same system (one feed comes from the owner of the system and the other from the aggregator), we believe that consumers are only interested in the feed from the source of truth (the feed from the owner of the system). We therefore propose to include in [systems.csv](https://github.com/MobilityData/gbfs/commits/master/systems.csv) only the feed from the owner of the system in case of a duplicate for the same system. Consumers, please let us know if you prefer using the feed URL from an aggregator instead of the feed from the owner of the system.

>part of the problem is that no where in the specification do we clearly define what constitutes a system

The current definition of `system_id` in the [specification](https://github.com/MobilityData/gbfs/blob/master/gbfs.md#system_informationjson) is : "Each distinct system or geographic area in which vehicles are operated MUST have its own unique `system_id`". I would be happy to accept a definition that clarifies this even further.

Thanks for your help!

**Comment by mplsmitch** [comment]
> In fact, we want a way to uniquely identify a system, not a feed. Unfortunately the system_id from system_information.json does not allow this because some operators use the same system_id for several distinct systems, as you correctly noted for Helbiz and Neuron.

What I'm suggesting is that we make an attempt at correcting the issues with how `system_id` is misused in stead of just relying on a workaround . I apologize if this is a dumb question but if you're removing duplicate feeds, couldn't the `discovery_url` be used as a unique identifier of a system?

> The current definition of system_id in the [specification](https://github.com/MobilityData/gbfs/blob/master/gbfs.md#system_informationjson) is : "Each distinct system or geographic area in which vehicles are operated MUST have its own unique system_id". I would be happy to accept a definition that clarifies this even further.

I don't think changing the `system_id` definition will do the trick. `system_id` says " Each distinct system" needs a unique ID but  there's nowhere in the spec that tells me what a "system" is. As it is right now, some operators interpret 'system" to mean a single market, like a city (city=system) and others interpret it to mean a single operator and all of the vehicles they operate across all cities (operator=system).  I believe it should be the former (city=system) but we haven't made that clear.

How we define what constitutes a "system" determines the scope of the data contained in a data set as well as the type of data.  For example, it's always been the intended that `system_information` would contain information about the local system so fields like `url` , `phone` and `email` would direct users to local points of contact if available.
In other words `url` should look like this:
`www.provider-name.com/city-name`
in stead of:
`www.provider-name.com`

This confusion also extends to the regions file because what constitutes a region isn't clearly defined. "Regions" were intended to represent a subset of "systems" but we have some producers doing the opposite of that and grouping multiple "systems" together and calling them regions. 

In #306 I proposed this, to be added to the [Term Definitions] section (https://github.com/MobilityData/gbfs/blob/master/gbfs.md#term-definitions) section: 

>**System:**
 GBFS data sets represent individual shared mobility systems bounded by a local geography. Systems SHOULD be defined by the geographic area in which vehicles are permitted to operate. Each system as represented by a single GBFS data set MUST have a unique system_id. Systems may span municipal or political boundaries in cases where vehicles are permitted to operate across multiple jurisdictions. If a user could reasonably expect to be able to rent a vehicle in one jurisdiction and return it in another, those jurisdictions would be considered a single system.
**Region**:
Regions as defined in system_regions.json are geographic areas defined within a shared mobility system. Regions may be defined for any purpose, for example political jurisdictions, neighborhoods or economic zones.

Related - there's also been discussion in the past about adding a unique identifier for providers/operators i.e. `provider_id`

**Comment by richfab** [comment]
Thanks @mplsmitch.

>make an attempt at correcting the issues with how `system_id` is misused 

I like this idea. For example, we could show a warning in the online [GBFS validator](https://gbfs-validator.mobilitydata.org/) when the `system_id` is already used by another system in systems.csv. 

We could also contact data producers who are not using the `system_id` correctly. But it will take time for operators to correct their data (Helbiz and Neuron have not responded to me since I mentioned the issue to them 6 months ago).

While waiting for `system_id` to be corrected and made unique across all feeds in systems.csv, we propose adding an 'ID' column to allow easier tracking and management of the feeds.

>couldn't the discovery_url be used as a unique identifier of a system?

That's a good suggestion. Unfortunately, the feed URL is not stable over time due to the multiple versions of the GBFS spec. Indeed, producers need to create a new URL for each major version so as not to break the integrations with consumers.

>I proposed this, to be added to the [Term Definitions] section

Great idea. I will open a new issue with your suggestion to add System and Region to the Term Definitions in the spec.

Thank you!

**Comment by richfab** [comment]
After analyzing the duplicates, we reduced the number of sources with duplicate `System ID` in [systems.csv](https://github.com/MobilityData/gbfs/blob/master/systems.csv) to only 2 sources: Helbiz and Voi. (Thank you to @gongmingqm10 for updating the `system_id` in the Neuron's feeds 🙏 )

That's why we are abandoning the idea of ​​adding an `ID` column in the [systems.csv](https://github.com/MobilityData/gbfs/blob/master/systems.csv) file.

Instead, we will work with micromobility.com (formerly Helbiz) and Voi to make the `system_id` unique in their feeds. 

Tagging @morten-skelmose at @voi-api and @imthatcarlos at @helbizofficial for visibility. 

More information about the `system_id` can be found in the [GBFS reference](https://github.com/MobilityData/gbfs/blob/master/gbfs.md#system_informationjson).

Thank you 🙏
