### ISSUE TITLE
consolidating station_information and station_status?

### ISSUE THREAD

**Issue by yocontra** [MobilityData/gbfs#77]
Maybe this has been thought of already, but doesn't it seem strange to issue two API calls to get:

- the name of the station
- how many bikes it can hold
- how many are available

It would be nice if there was a single object that represents a station, with a single endpoint to get the information for the stations in the system.

**Comment by afischer** [comment]
Hey there!

As someone who has worked with GFBS data quite a bit, I initially had the same thought, but have since come around to the separation of the feeds.

`station_information.json` is intended to provide fairly immutable data—the location of a station or it's name is not likely to change on a short time scale.

`station_status.json` is meant to contain the real-time, rapidly changing information regarding the station.

This separation of interests can save you time/data when building applications or APIs on top of GBFS. For example, on app load, pull both feeds and merge their information. While this is slightly more complex than having a single feed, subsequent updates can just query `station_status.json` without having to re-query the information that is unlikely to change. Make sure to  query updates to `station_information.json` periodically, but it's not necessary to be checking that feed every time you want to update station data.

**Comment by heidiguenin** [comment]
Hey @contra and @afischer  - I'm going to go ahead and close this one down for now. Thanks!

**Comment by yocontra** [comment]
@HeidiMG What is the process for reopening this? Still a valid issue.

**Comment by heidiguenin** [comment]
@contra done

**Comment by yocontra** [comment]
@HeidiMG Thanks! Still want to have a discussion about this but the governance for the spec is unclear to me, so not sure who needs to be involved.

**Comment by heidiguenin** [comment]
We'll be working on clarifying governance soon. But for now, anyone can/should chime in with thoughts about your question and the response @afischer gave.

**Comment by Noe-Santana** [comment]
Hello @contra, I think that I share part of your concern, but, at the end I´m agree with @afischer, the dynamics of both data sources are different, the "station_information" is more stable than the "station_status", so, deppending on the needings of the aplication each one can be refreshed on an independent sched. 

I got to this issue because I found some inconsistencies in the relation between these two tables, I just opened a new isse about that; #223

**Comment by Empty2k12** [comment]
@contra You use case seems to be the perfect fit for a product we're developing: With [mapintelligenceagency/gbfsQL](https://github.com/mapintelligenceagency/gbfsQL), you can expose GBFS-Feeds as a GraphQL API, saving bandwidth on all clients interacting with the data.

Currently, GbfsQL merges relevant feeds, so you could easily request for example `station_information` and/or `system_alerts` when querying for stations. See this query taken from our application:

```
query {
  Velocity {
    stations {
      lat
      lon
      name
      currentStatus {
        is_renting
        num_bikes_available
        num_docks_disabled
        num_docks_available
      }
      currentSystemAlerts {
        type
        summary
        description
      }
    }
  }
}
```

It also adds real-time updates via GraphQL Subscriptions, so you can benefit from getting updates incrementally.

While GbfsQL is still under development and not ready for public use, we have been running it on our staging environment for some weeks without any problems. I'd really appreciate your input if you find this might be a solution for you. With any questions or problems, feel free to contact me at gero@mapintelligence.agency
